name: Deploy to Preview Channel

on:
    push:
        branches:
            - dev

jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}"
                  firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MUFFIN_LINKER }}"
                  expires: 30d
                  projectId: muffin-linker
                  channelId: dev